### PR TITLE
Instructions added

### PR DESCRIPTION
**Pull request by mariblan**
I added some instructions to the index.html of the git&github workshop folder.

### CODE REVIEW

**Comment by mariblan** [comment]
Something is not working, fix that.!

**Review by Pia-Koester — APPROVED** [review]
Looks good.

**Review by nsentissi — APPROVED** [review]
nice !

**Review by AnthonyEmm — APPROVED** [review]
I approve!

**Review by bishaldiganta — APPROVED** [review]
Good job!

**Comment by biernard1988** [comment]
I approved it, 10$ pls.

**Review by M-Pedrami — APPROVED** [review]

**Review by xhenigega — APPROVED** [review]

**Review by biernard1988 — COMMENTED** [review]
ok

**Pull request merged**
